FORMAT: 1A

# PMC Edge API

Api of the PMC edge project

## PositionPeriod Screen [/position_periods/{position_id}/{period_id}]


+ Model (application/hal+json)

+ Parameters
    + position_id (required, number, `1`) ... ID of the position in the form of an integer
    + period_id (required, number, `1`) ... ID of the period in the form of an integer
+ Attributes (object)
    + employee
        + name: Gina Williams
        + surname: Williams
        + photography: 2014/2/11/1392112142_7790_9331
        + id: 1006
        + position_name: Senior Product Manager
        + position_id: 136
    + current_period (PeriodGoals)
    + next_period (PeriodGoals)


### GET PositionPeriod Screen [GET]

A single Employee is returned through a GET request where the employee id is sent as an URL parameter.

+ Request (application/json)

    + Headers
    
            Accept-Charset: application/json
            X-AUTH-TOKEN: DEBUGTOKEN
            X-FORWARDED-HOST: mmbeta-133.umantis.lan
            
+ Response 200 (application/hal+json)

    + Headers
    
    + Body
    + Attributes (PositionPeriod Screen)


# Data Structures

## PeriodGoals
+ id: 103
+ period_name: 2015
+ period_evaluation: AA - Very good
+ goals_with_feedback (array[GoalsWithFeedback])

## GoalsWithFeedback
+ type: 1
+ id: 1548
+ goal_title: Create a good gateway
+ received_feedbacks: 0
+ total_feedbacks: 2